version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    # Raise pull requests for version updates
    # to cargo against the `develop` branch
    target-branch: "develop"
    # Labels on pull requests for version updates only
    labels:
      - "cargo dependencies"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    # Raise pull requests for version updates
    # to cargo against the `develop` branch
    target-branch: "develop"
    # Labels on pull requests for version updates only
    labels:
      - "cargo dependencies"