/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vade_evan_Vade */

#ifndef _Included_com_vade_evan_Vade
#define _Included_com_vade_evan_Vade
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vade_evan_Vade
 * Method:    executeVade
 * Signature: (Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_vade_evan_Vade_executeVade
  (JNIEnv *, jclass, jstring, jobjectArray, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
